import { Router } from "express";
import { authRoutes } from "./auth.routes.js";
import { adminRoutes } from "./admin.routes.js";
import { factoryRoutes } from "./factory.routes.js";
import { staffRoutes } from "./staff.routes.js";
import { projectsRoutes } from "./projects.routes.js";
import { customersRoutes } from "./customers.routes.js";
import { vendorsRoutes } from "./vendors.routes.js";
import { servicesRoutes } from "./services.routes.js";
import { stockRoutes } from "./stock.routes.js";
import { wasteRoutes } from "./waste.routes.js";
import { notificationsRoutes } from "./notifications.routes.js";
import { invoicesRoutes, transactionsRoutes } from "./finance.routes.js";
import { subscriptionRoutes } from "./subscriptions.routes.js";
export const apiRoutes = Router();
apiRoutes.use("/auth", authRoutes);
apiRoutes.use("/admin", adminRoutes);
apiRoutes.use("/factories", factoryRoutes);
apiRoutes.use("/staff", staffRoutes);
apiRoutes.use("/projects", projectsRoutes);
apiRoutes.use("/customers", customersRoutes);
apiRoutes.use("/vendors", vendorsRoutes);
apiRoutes.use("/services", servicesRoutes);
apiRoutes.use("/stock", stockRoutes);
apiRoutes.use("/waste", wasteRoutes);
apiRoutes.use("/notifications", notificationsRoutes);
apiRoutes.use("/transactions", transactionsRoutes);
apiRoutes.use("/invoices", invoicesRoutes);
apiRoutes.use("/admin/subscriptions", subscriptionRoutes);
